# -*- coding: utf-8 -*-
"""PythonPractice2-Saranya.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SqAgX7R86LgDX4sKPSPnXkh3kcjm4A5e
"""

# Practice 1
word = input("Enter a word:")
wordlist = list(word)
wordset = set(word)
for letter in wordset:
   print(f"{letter} = {wordlist.count(letter)}")

# Practice 2
print("Enter three Numbers:")
num1 = int(input("Number 1:"))
num2 = int(input("Number 2:"))
num3 = int(input("Number 3:"))
if num1 > num2 and num1 > num3:
  print(f"Greatest is: {num1}")
elif num2 > num1 and num2 > num3:
  print(f"Greatest is: {num2}")
else:
  print(f"Greatest is: {num3}")

# Practice 3
base = int(input("Enter the base:"))
expo = int(input("Enter the exponent:"))
ans = base ** expo
print(f"output= {ans}")

# Practice 4
num = int(input("Enter the number:"))

def sumOfCubes(num):
  sum = 0
  for i in range(1, num):
    sum = sum + i ** 3
  print(f"Sum of cubes :{sum} ")

sumOfCubes(num)

# Practice 5
def fizzBuzz():
    for i in range(1,11):
      if i % 2 == 0 and i  % 5 == 0:
        print("FizzBuzz")
      elif i % 2 == 0:
        print("Fizz")
      elif i % 5 == 0:
        print("Buzz")
      else:
        print(f"{i}")


fizzBuzz()

# Practice 6
numlist = [2, 3, 4, 2, 5, 2, 3]
numset = set(numlist)
maxitem = numlist[0]
for i in numset:
  if numlist.count(i) > numlist.count(maxitem):
    maxitem = i
print(f"Most repeated item = {maxitem}")

# Practice 7
count = int(input("Enter the count of list:"))
mylist = []
for i in range(0,count):
  x = int(input(f"Enter {i+1}th element: "))
  mylist.append(x)

sum = 0
for i in range(0,count):
  sum = sum + mylist[i] ** 2
print(f"My List:{mylist}")
print(f"Sum of squares of list: {sum}")

# Practice 8
for l in range(1,16):
  if l % 2 == 0:
    print(f"{l} Even")
  else:
    print(f"{l} Odd")

# Practice 9
tempF = int(input("temperature in Farenheit:"))
tempC = ((tempF - 32) / 9) * 5
print(f"Temperature in Celcius = {tempC}")

# Practice 10
num = int(input("Enter the number:"))
def factorial(num):
  if num == 1:
    return 1
  else:
    return num * factorial(num - 1)
fact = factorial(num)
print(f"Factorial of {num} is {fact}")

